### ISSUE TITLE
Compatibility with Docker?

### ISSUE THREAD

**Issue by inacho** [aloisklink/remark-mermaid-dataurl#5]
It seems that Docusaurus builds (`npm run build`) fail when this plugin is a dependency and the build is executed in Docker.

This is my Dockerfile used to compile Docusaurus:

```dockerfile
FROM node:alpine as builder
USER node
COPY --chown=node:node . /home/node/app
WORKDIR /home/node/app
RUN npm install && npm run build

FROM nginx:alpine
COPY --from=builder /home/node/app/build /usr/share/nginx/html
```

Extract of the output of the build:

```
#9 113.7 ./docs/test.md
#9 113.7 Error: /home/node/app/node_modules/@mermaid-js/mermaid-cli/index.bundle.js with kwargs {"input":"/tmp/remark-mermaid-HkEIAA/input","output":"/tmp/remark-mermaid-HkEIAA/output.svg"} failed with error code: 1
#9 113.7  @ ./.docusaurus/registry.js 1:2724-2803 1:2562-2662
#9 113.7  @ ./node_modules/@docusaurus/core/lib/client/exports/ComponentCreator.js
#9 113.7  @ ./.docusaurus/routes.js
#9 113.7  @ ./node_modules/@docusaurus/core/lib/client/clientEntry.js
```

The issue can be reproduced as well when trying to execute the unit tests of this repo inside Docker:

```bash
docker run -v `pwd`:`pwd` -w `pwd` node:10.17 /bin/bash -c 'npm install && npm run test'
```

![tests-docker](https://user-images.githubusercontent.com/742624/107461628-c25f6000-6b9d-11eb-85dd-f947530215e0.png)

Is there any part of the code that is not compatible with Docker?
Thanks in advance

**Comment by mister-what** [comment]
Hi @inacho,
#6 will hopefully fix this issue
